### ISSUE TITLE
不支持WebSocket

### ISSUE THREAD

**Issue by zesys** [ffay/proxygateway#14]
不支持WebSocket，使用ws://localhost 请求返回的状态是200，而非WebSocket的长连接状态101。能处理支持吗？

**Comment by ffay** [comment]
我之前测试是支持WebSocket的，关键是看你后端服务是否支持

**Comment by zesys** [comment]
> 我之前测试是支持的WebSocket的，关键是看你后端服务是否支持
单独访问服务器后端WebSocket的响应是正常的，只要通过proxygateway就不正常。
