### ISSUE TITLE
为什么打开报错?

### ISSUE THREAD

**Issue by zack-sys** [ffay/proxygateway#16]
System error, please try again later 这个错误

**Comment by zack-sys** [comment]
解决了.数据库的问题

**Comment by joshuazm** [comment]
我也是这个问题，数据库也是正确配置了哒。。你的数据库问题出在哪里？

**Comment by joshuazm** [comment]
> 解决了.数据库的问题

我也是这个问题，数据库也是正确配置了哒。。你的数据库问题出在哪里？
